### ISSUE TITLE
Issuing of a VerifiableId fails (error 404)

### ISSUE THREAD

**Issue by ahmedsmiai** [walt-id/waltid-web-wallet-deprecated#101]
An error occurs in the redirection to web wallet whenever I try to issue a credential (issuer portal) or connect wallet using verifiable id (verifier portal) 

steps to reproduce

select a credential and confirm ( https://issuer.walt.id/  ) 
![image](https://user-images.githubusercontent.com/47064156/209482190-c1b79994-c63d-44df-b010-0b78e8c9b259.png)
![image](https://user-images.githubusercontent.com/47064156/209482196-be589fe1-6409-41f6-bfcd-d25f080a1e66.png)

and 

connect wallet using verifiable id ( https://verifier.walt.id/ )
![image](https://user-images.githubusercontent.com/47064156/209482208-75de3339-debc-49a9-a70f-4ec3ed12382b.png)
![image](https://user-images.githubusercontent.com/47064156/209482213-342a3cb3-3590-4b6e-8c12-5d9c3cb29222.png)

**Comment by philpotisk** [comment]
@ahmedsmiai please retest with a clear cache (private browser window)

**Comment by cpatsonakis** [comment]
Closing this issue as the code in this repository is deprecated (as its name implies). For a more up-to-date web wallet UI, refer to our more recent community edition identity stack that is actively maintained and updated in the [waltid-identity]() repository.
