### ISSUE TITLE
Link to get token for the EBSI Pre Production environment is broken 

### ISSUE THREAD

**Issue by ahmedsmiai** [walt-id/waltid-web-wallet-deprecated#102]
1- settings
![image](https://user-images.githubusercontent.com/47064156/209332706-f4dd3f5c-27cd-400c-85f1-368cc36700bd.png)

2- Ecosystems
![image](https://user-images.githubusercontent.com/47064156/209332766-2f41d955-2313-4d0a-aace-526b29d6ee5f.png)

3- EBSI/ESSIF (add)
![image](https://user-images.githubusercontent.com/47064156/209332828-69cbaed0-95c7-4296-8cda-cb73f985a771.png)

4- click on (here) to get a token
![image](https://user-images.githubusercontent.com/47064156/209332978-8462c67a-92cf-48dc-bf4e-f2fc36c768d9.png)

![image](https://user-images.githubusercontent.com/47064156/209333016-875dedc1-1105-4a1a-b007-12663bcb7d72.png)

**Comment by cpatsonakis** [comment]
Closing this issue as the code in this repository is deprecated (as its name implies). For a more up-to-date web wallet UI, refer to our more recent community edition identity stack that is actively maintained and updated in the [waltid-identity]() repository.
