### ISSUE TITLE
The expiring date must be after the issuance date 

### ISSUE THREAD

**Issue by ahmedsmiai** [walt-id/waltid-web-wallet-deprecated#104]
In the details page of these credentials, the expire date is before the issuance date:

![image](https://user-images.githubusercontent.com/47064156/210371912-4f7eb686-8a6b-4801-9930-e79ea8b645b1.png)

![image](https://user-images.githubusercontent.com/47064156/210372087-14e8a471-0f4d-4e4c-aeba-15c44476ff35.png)

![image](https://user-images.githubusercontent.com/47064156/210372622-1f7afd8d-b3b7-4755-a1e3-c3fb27c6be80.png)

**Comment by cpatsonakis** [comment]
Closing this issue as the code in this repository is deprecated (as its name implies). For a more up-to-date web wallet UI, refer to our more recent community edition identity stack that is actively maintained and updated in the [waltid-identity]() repository.
