### ISSUE TITLE
Presentation of credential error

### ISSUE THREAD

**Issue by ahmedsmiai** [walt-id/waltid-web-wallet-deprecated#111]
After issuing an obc, the infos aren't shown in the web wallet, although I can copy the credentials as shown in the screenshot

![image](https://user-images.githubusercontent.com/47064156/216331527-fe0fe389-1d8f-4066-ae7a-f70919097350.png)

**Comment by cpatsonakis** [comment]
Closing this issue as the code in this repository is deprecated (as its name implies). For a more up-to-date web wallet UI, refer to our more recent community edition identity stack that is actively maintained and updated in the [waltid-identity]() repository.
