### ISSUE TITLE
Signin page

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-web-wallet-deprecated#16]
In addition to the "login" page we need a "signup" page.

As we need to support login as well as signup in the scope of the issuance-flow, we think it is best to implement both functions on a "signin" page. The reason is that when being redirected from the issuance-portal, the user should not loose all parameters in the URL (see screenshot).

![image](https://user-images.githubusercontent.com/55081379/145632600-a77e4ba6-f423-43fd-b7d3-b1a5ce43ff9b.png)

The user should be able to switch from "login" to "signup" page without the link being changed (no page reload).

**Comment by iietmoon** [comment]
I think we can do it like the wizard, same page but conditional components? so we  don't lose the params of the url

**Comment by philpotisk** [comment]
> I think we can do it like the wizard, same page but conditional components? so we don't lose the params of the url

@iietmoon exatly! please go ahead and implement it this way.

**Comment by iietmoon** [comment]
I pushed a new commit with login, signup, rest password as a wizard, currently, I need just to know how I can integrate new registration because no mention of it in the API documentation
