### ISSUE TITLE
Show Credential Claims during Presentation Exchange

### ISSUE THREAD

**Issue by fabian-hk** [walt-id/waltid-web-wallet-deprecated#19]
We from yes.com would like to have the credential claims displayed during presentation exchange so that the user knows what data is shared with the verifier. In the image below you can see what this could look like. Would this be something you consider implementing?

![PresentationExchange](https://user-images.githubusercontent.com/50799747/150351028-250b499c-e986-4ba1-bfdb-2eafb444bbf1.png)

**Comment by tlodderstedt** [comment]
As an addition: the current implementation only shows the DID. I would assume this is not really meaningful to a holder and it does not allow the holder to differentiate between different credentials of the same type. 
I think displaying the user claims is best practice.

**Comment by philpotisk** [comment]
Currently all the claims are shown if the credential is clicked. This allows the user to review all the details that are being shared:

![image](https://user-images.githubusercontent.com/55081379/150631833-cdb0e70c-86cc-4969-a510-65ead2d7b1b1.png)

We definitely can think of how the UX can be improved. What do you think @dombrn & @oussema ?

**Comment by cpatsonakis** [comment]
Closing this issue as the code in this repository is deprecated (as its name implies). For a more up-to-date web wallet UI, refer to our more recent community edition identity stack that is actively maintained and updated in the [waltid-identity]() repository.
