### ISSUE TITLE
Log in does not work when using a HTTP connection

### ISSUE THREAD

**Issue by ohylli** [walt-id/waltid-web-wallet-deprecated#33]
If the wallet is used via a HTTP connection (excluding localhost) the log in does not work. This is because the crypto.subtle used in hashing the log in email and password is only available in secure contexts see for example [crypto.subtle in MDN](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle). Now if the wallet was a production ready system it would be perfectly reasonable to see this as a non issue since you should use HTTPS anyway. But since this is currently meant for just demo use I believe, I think it is reasonable to be able to host this just using HTTP as for example we are currently doing.

One solution to this could be making the use of hashing a configurable option. Another benefit of making hashing optional would be to make debugging easier. If you want to explore the files the wallet has created for the user, it is easier to find them if the email has not been hashed since that is used to name the folder.

**Comment by severinstampler** [comment]
fixed
