### ISSUE TITLE
Login page (wallet)

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-web-wallet-deprecated#4]

**Comment by philpotisk** [comment]
- [x] Validation of Email (valid email)
- [x] Validation of PW (not-emtpy)
- [x] Forward Email/PW to the backend via NuxtJS (auth module)

**Comment by iietmoon** [comment]
@philpotisk @severinstampler 
I made validation in` "email-PW-validation"` branch, 
I don't know if I need add validation not just empty but can be for specified chars and minimum

**Comment by philpotisk** [comment]
@iietmoon I reviewed the update. here my feedback:

the message-box is good! we can use this for all kind of notifications, right?

for the pw-validation it seems we have two kind of validation-systems. one is inline (e.g. if no @ is in the message), and the one you have implemented (e.g if no domain is specified). Is it possible to only use one system for all kind of errors?

please complete the these two functions:
- [x] Validation of Email (valid email)
- [x] Validation of PW (not-emtpy)

and open a PR.

thx

**Comment by iietmoon** [comment]
@philpotisk Yes I can turn the message box to be a reusable component "Error, Success" with a message param.

if PW is empty or typed then cleared will show that input in the red border, not just the message box because the message show just in submit condition.
But I will do an async validation

**Comment by iietmoon** [comment]
@philpotisk 
in the last commit, I  turned the error message to be a reusable component with two props "is-active" & "message".
and I did a condition to check if email & PW is validated, is both not validated, is just email not validate, is just password not validate. and the login attempt response message.
so when you type and return an error you will know exactly where the error

**Comment by iietmoon** [comment]
@philpotisk  Please recheck this!
