### ISSUE TITLE
Creating a DID:WEB not possible

### ISSUE THREAD

**Issue by kaimeinke** [walt-id/waltid-web-wallet-deprecated#51]
As a user I want to onboard the DID:WEB ecosystem by creating a DID. 

Bug:

The creation ist not possible, the process can not be completed successfully.

![image](https://user-images.githubusercontent.com/59994024/167484160-e2eff08b-ef98-4358-8fe5-527656ce3421.png)

Tested on:
- https://wallet.walt.id/
- https://wallet.waltid.org/ (404)
- https://wallet.lab.gaia-x.eu/

**Comment by kaimeinke** [comment]
There is a CORS error with the DID:WEB 
![image](https://user-images.githubusercontent.com/59994024/167484964-388370e9-4b01-4488-bad4-e2256717c816.png)

**Comment by severinstampler** [comment]
fixed, the problem was due to a hardcoded server url when resolving the did from the API after creation.

**Comment by philpotisk** [comment]
@severinstampler please redeploy, as there are still old URLs pointing to waltid.org in the system. thx

![image](https://user-images.githubusercontent.com/55081379/169219737-3655fe65-0a86-46fa-8169-902f9acb6df6.png)

**Comment by severinstampler** [comment]
no I redeployed it yesterday. Please refresh your cache
