### ISSUE TITLE
No button to contiue the user journey after EBSI/ESSIF onboarding

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-web-wallet-deprecated#52]
![Screenshot from 2022-05-04 14-51-03](https://user-images.githubusercontent.com/55081379/168060168-7c7eb240-3a33-4243-81c2-eb4199435ead.png)

- The there should be a button to bring the user to the did:list
- The image on this page should be centered.

**Comment by cpatsonakis** [comment]
Closing this issue as the code in this repository is deprecated (as its name implies). For a more up-to-date web wallet UI, refer to our more recent community edition identity stack that is actively maintained and updated in the [waltid-identity]() repository.
