### ISSUE TITLE
Heavy unused static images 

### ISSUE THREAD

**Issue by rigwild** [walt-id/waltid-web-wallet-deprecated#58]
130 MB of images are stored in the repository and does not seem to be referenced anywhere.

Looks like only [background/12.png](https://github.com/walt-id/waltid-web-wallet/blob/a28b090054f6c22e29c86f5d9cd7b52a6c2b86aa/static/background/12.png) is used here:
https://github.com/walt-id/waltid-web-wallet/blob/a28b090054f6c22e29c86f5d9cd7b52a6c2b86aa/assets/css/core.css#L135

Directories: 
- [background](https://github.com/walt-id/waltid-web-wallet/tree/a28b090054f6c22e29c86f5d9cd7b52a6c2b86aa/static/background)
- [bg](https://github.com/walt-id/waltid-web-wallet/tree/a28b090054f6c22e29c86f5d9cd7b52a6c2b86aa/static/bg)

![image](https://user-images.githubusercontent.com/26366184/175842835-e73799dd-9e7f-4c21-880a-b5d91648d88e.png)

Unused images should be removed, and [12.png](https://github.com/walt-id/waltid-web-wallet/blob/a28b090054f6c22e29c86f5d9cd7b52a6c2b86aa/static/background/12.png) compressed.

**Comment by cpatsonakis** [comment]
Closing this issue as the code in this repository is deprecated (as its name implies). For a more up-to-date web wallet UI, refer to our more recent community edition identity stack that is actively maintained and updated in the [waltid-identity]() repository.
