### ISSUE TITLE
[Wallet] Fetch chain list from connected wallet

### ISSUE THREAD

**Issue by mikeplotean** [walt-id/waltid-web-wallet-deprecated#77]
Currently, the chain list is hard-coded as follows:
* metamask - polygon, mumbai, ethereum
* tezos (temple) - tezos, ghostnet

The request is to remove the hard-coded values and fetch the chains available in the connected wallet (e.g. metamask, temple, coinbase etc.)

**Comment by cpatsonakis** [comment]
Closing this issue as the code in this repository is deprecated (as its name implies). For a more up-to-date web wallet UI, refer to our more recent community edition identity stack that is actively maintained and updated in the [waltid-identity]() repository.
