### ISSUE TITLE
Get Chain List From Connected Wallet

### ISSUE THREAD

**Issue by taminobaumann** [walt-id/waltid-web-wallet-deprecated#78]
When opening the menu item `NFTs` in the wallet. The chain list dropdown which is used to switch the chain, where the NFTs are displayed from, shouldn't be a list which is hard-coded. It should rather be fetched from the wallet or another source of trust, to always stay up to date with latest chain changes.

**Comment by cpatsonakis** [comment]
Closing this issue as the code in this repository is deprecated (as its name implies). For a more up-to-date web wallet UI, refer to our more recent community edition identity stack that is actively maintained and updated in the [waltid-identity]() repository.
