### ISSUE TITLE
DID selection

### ISSUE THREAD

**Issue by severinstampler** [walt-id/waltid-web-wallet-deprecated#8]
Menu (or likewise) to select DID, for which actions in the wallet are executed.
Actions depending on the DID include: list credentials, share credentials, receive credentials

**Comment by philpotisk** [comment]
@severinstampler How is it possible to set the default DID? Do we need to extend the backend API to define the default DID?

**Comment by severinstampler** [comment]
yes in some way we will need to store the information, which did is currently selected, so that it behaves more predictably.

**Comment by philpotisk** [comment]
Meanwhile the did-selection is possible at: settings -> ecosystems -> select
