### ISSUE TITLE
NFTs Settings Modal

### ISSUE THREAD

**Issue by taminobaumann** [walt-id/waltid-web-wallet-deprecated#87]
- [x] Add [adjustment icon](https://d.pr/i/Wuxld5) next to the search. When clicked, it should open the NFTs Settings modal -> [screenshot](https://d.pr/i/wMjY6C)
- [x] Add the NFTs Settings modal | [Figma reference](https://www.figma.com/file/xv7Yjy3TKcIoWb5660r9Ou/Cloud-Platform-UI?node-id=686%3A4351). The dropdown should be a replacement for the dropdown on the [main /nft page](https://d.pr/i/Ld6wwN).

**Comment by farahaidid** [comment]
@taminobaumann i am confused with "NFTs Settings modal" and "Dropdown"
figma reference is dropdown, and we have nft dropdown in /nfts page,

actually, what is "NFTs Settings modal"?

**Comment by taminobaumann** [comment]
@farahaidid. I've recorded a [video](https://www.loom.com/share/e119630470244cd88c61300826892b12), where I explain the idea. Hope it helps and makes things clearer.

**Comment by farahaidid** [comment]
thank you, now i am clear
