### ISSUE TITLE
[Web-Wallet] Support ipfs:// image urls

### ISSUE THREAD

**Issue by taminobaumann** [walt-id/waltid-web-wallet-deprecated#88]
Data of NFT: https://d.pr/i/R0KFXK

Currently, the supported ipfs urls have the form:
```ipfs://bafkreifwhiexbrxor4nxrzacmgvebrvtc4qyjnsuhongccmiss4lhqkosa```
This doesn't work for ipfs urls such as:
```ipfs://QmUJHhdEUQxbqKMwb25iRU39dnbwrWxCZvkefjLknziTnd/0.jpg```

Check the ipfs url standards and add support accordingly.

**Comment by mikeplotean** [comment]
Supporting urls:
* cidv0 - `ipfs://{Qm-cid-46-char}`
* cidv1 - `ipfs://{bafy-cid-59-char}`
* resource location: `ipfs://{cid}/path/to/resource/file.ext`
