### ISSUE TITLE
Update 09.11

### ISSUE THREAD

**Issue by taminobaumann** [walt-id/waltid-web-wallet-deprecated#92]
- When new chain is selected in the dropdown menu in the NFT settings modal, the modal should be closed automatically
- Display current selected chain [here](https://d.pr/i/6GZ4dZ). Make text of the selected chain clickable, color should be black and no underline style. When clicked, it should open the NFT Settings modal.

**Comment by farahaidid** [comment]
https://www.loom.com/share/330bdbf9121548ba8f6f057405a9e9c1
@taminobaumann

**Comment by taminobaumann** [comment]
Hey @farahaidid, thanks for the update. Looks great.

Feedback:
What would be great, if we could show a loading spinner after the user selected a new chain via the dropdown, that we don't close the modal immediately, but replace the modal body [as follows](https://www.figma.com/file/xv7Yjy3TKcIoWb5660r9Ou/Cloud-Platform-UI?node-id=754%3A4330&t=rZnrqFEhcYZiUb0r-0) and close it as soon as the frontend has processed the change.

**Comment by farahaidid** [comment]
<img width="549" alt="Screenshot 2022-11-13 at 2 30 18 PM" src="https://user-images.githubusercontent.com/37977683/201513014-bdc9705e-7f72-4046-89b9-8669da8f7df0.png">

@taminobaumann

**Comment by taminobaumann** [comment]
@farahaidid That is perfect. Thanks!
