### ISSUE TITLE
UI Overflow issue on ecosystems page

### ISSUE THREAD

**Issue by taminobaumann** [walt-id/waltid-web-wallet-deprecated#97]
issue on the following page: /settings/ecosystems
as well as when a click on the same page the "Select Ecosystem" button

- [x] Add the overflowing options into a fixed width div which is scrollable | [image](https://d.pr/i/IUrdZp)
- [x] Overflowing problem continues to occur | [video](https://www.loom.com/share/f5b093546291432088be888d4c6b919c)
-> How to create multiple dids to create the overflowing problem for testing | [video](https://www.loom.com/share/4e0dc3ef18bc43079a00a36826a383c1)

**Comment by taminobaumann** [comment]
@farahaidid still experiencing some issues. See above.

**Comment by farahaidid** [comment]
issue is wrong css throughout the application,
fixing this issue , need to change base css in almost every pages

**Comment by taminobaumann** [comment]
@farahaidid Thanks a lot for the update! Now it looks much better.  Could you please have a look on the login page again. There the general width which the components are getting seems a bit less. See [image](https://d.pr/i/92TSjS). It is for mobile as well as desktop. Thanks!!
