### ISSUE TITLE
View button for account management isn't working

### ISSUE THREAD

**Issue by ahmedsmiai** [walt-id/waltid-web-wallet-deprecated#99]

**Comment by ahmedsmiai** [comment]
https://wallet.walt-test.cloud/settings
https://wallet.walt.id/settings

**Comment by ahmedsmiai** [comment]
1- 
![image](https://user-images.githubusercontent.com/47064156/206732198-cf697281-c0ea-47b1-b53d-30741ca85442.png)
2- setting/reglage
![image](https://user-images.githubusercontent.com/47064156/206732323-bd11009d-5cc3-452e-8c71-8a57205afa72.png)
3-  View (account)
![image](https://user-images.githubusercontent.com/47064156/206732463-fc1a76ae-f55b-4f37-984e-c81dac701958.png)

**Comment by philpotisk** [comment]
Currently this button has no functionality yet.

I think it makes sense that we create a page at settings/account and simply show the account-name (email address or blockchain address).

@farahaidid can you work on this one?

**Comment by farahaidid** [comment]
<img width="1679" alt="Screenshot 2022-12-10 at 3 15 20 PM" src="https://user-images.githubusercontent.com/37977683/206842829-a9f6a0f1-37e3-495d-9594-fc98ad9811ea.png">

@philpotisk
